name: match_making
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  autocomplete_textfield: ^1.7.3

  firebase_auth: ^0.16.1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.1
  provider: ^4.1.3
  get_it: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  test:

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/tiers/

  fonts:
    - family: RIXGOB
      fonts:
        - asset: fonts/RIXGOB.TTF
    - family: RIXGOM
      fonts:
        - asset: fonts/RIXGOM.TTF 