name: match_making
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI-related
  cupertino_icons: ^0.1.3
  autocomplete_textfield: ^1.7.3
  progress_dialog: ^1.2.4
  fluttertoast: ^7.0.1
  flutter_native_admob: ^2.1.0

  # Auth
  firebase_auth: ^0.16.1
  flutter_facebook_login: ^3.0.0
  flutter_twitter_login: ^1.1.0
  google_sign_in: ^4.5.1

  # Util
  validators: ^2.0.0
  shared_preferences: ^0.5.8
  firebase_remote_config: ^0.3.1
  intl: ^0.16.1

  # State Management
  provider: ^4.3.0

  # Network
  http: ^0.12.2
  http_interceptor: ^0.3.2
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1

  json_serializable: ^3.4.0
  build_runner: ^1.10.1

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/tiers/

  fonts:
    - family: RIXGOB
      fonts:
        - asset: assets/fonts/RIXGOB.TTF
    - family: RIXGOM
      fonts:
        - asset: assets/fonts/RIXGOM.TTF