name: Dart CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with: 
        java-versions: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get
    
    - name: Run test
      run: flutter test

    - name: Build apk
      run: flutter build apk
